version: '3.8'

services:
  opensearch:
    image: opensearchproject/opensearch:2.14.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${PASSWORD}
      - plugins.security.disabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"   # OpenSearch API
      - "9600:9600"   # Performance analyzer
    networks:
      - opensearch-net

  dashboards:
    image: opensearchproject/opensearch-dashboards:2.14.0
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"   # Dashboard UI
    environment:
      - OPENSEARCH_HOSTS=https://opensearch:9200
      - OPENSEARCH_USERNAME=${USERNAME}
      - OPENSEARCH_PASSWORD=${PASSWORD}
      - OPENSEARCH_SSL_VERIFICATIONMODE=none
    depends_on:
      - opensearch
    networks:
      - opensearch-net

networks:
  opensearch-net:
